# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93e0c07173afad99051b3bce2790fc3d0dea5a1b097969205346d3913e9a5770e242b333d13418de82312eb8a70bf5d4884c254357d8f99500ec46a81ed15a64

test:
  secret_key_base: 251bcc8eb8f08394e03545ec84cdcefc98d67844539b5d5028aea8959d92f6cbba8d94dc3a215c3b121162db3c86f701be9fa73c0d825c5181de1ebca9c38acf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
